spring:
  application:
    name: product-service

#  h2:
#    console:
#      enabled: true
  datasource:
#    url: jdbc:postgresql://ep-floral-haze-ao8mzl9f-pooler.c-2.ap-southeast-1.aws.neon.tech/product?sslmode=require&channel_binding=require
    url: jdbc:mysql://localhost:3307/tanmay
    username: tanmay
    password: tanmay
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
